app:
  database:
    url: jdbc:mysql://localhost:3306/dbo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    poolName: Pool
    maxPoolSize: 50
    minPoolSize: 10
    maxLifetime: 50000
    validationTimeout: 250

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true

#server:
#    port: 3000

security:
  basic:
    enable: false
  ignored: /**